<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Chris Turner" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Exploring Changes Throughout the 21st Century Between GNE, Malnourished Population Percentage, and Unemployment Rate</title>
    <meta name="generator" content="Hugo 0.110.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/post/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project/project2/">Exploring Changes Throughout the 21st Century Between GNE, Malnourished Population Percentage, and Unemployment Rate</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 19, 2023 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>We initially wanted to obtain datasets to explore the relationships between food, food insecurity, and prices. However, due to not meeting the initial dataset constraints, we pivoted and decided to develop datasets instead, using data housed in the World Development Indicators database (<em>World Development Indicators.org)</em>. These variables were selected because the potential relationships amongst the datasets could be interesting and valuable in shaping how we examine the effect that standard country metrics could be affected by or related to how much of the country’s population is malnourished.</p>
<p>To tidy the datasets, we had to condense the individually broken-up year columns into a singular one using pivoting functions. After this, string replacement was needed to format the year columns to not include extraneous information in the entries and to have them simply in the year digit format. From there, we re-coded column entries of numeric columns to be numeric rather than characters. We then removed redundant columns that did not contribute new information to the overall dataset. Lastly, we removed entries of the format “..” as this was how the database decided to encode missing values.</p>
<p>Some potential relationships we expect to see in our datasets are that a country will tend to have a lower life expectancy and a higher malnourishment percentage if its Gross National Expenditure (GNE) is lower. A country with a high percentage of unemployment will be positively correlated with a lower GNE. Our paper will explore the following research questions: Firstly, can a country’s average lifespan be classified as above or below the average lifespan in 2019 using its percentage of the malnourished population and unemployment rate? Secondly, can a country’s average lifespan be classified as above or below the average using all a country’s GNE, unemployment rate, malnourished population percentage, year ?</p>
<pre class="r"><code>#Load Packages
library(tidyverse)
library(readr)
library(ggplot2)
library(factoextra)
library(cluster)
library(readr)
library(plotROC)

#load datasets
gne &lt;- read_csv(&quot;gdp.csv&quot;, show_col_types = FALSE)
life_expec_malnourish &lt;- read_csv(&quot;life_expec_malnourish.csv&quot;, show_col_types = FALSE)
perc_unemplyed &lt;- read_csv(&quot;perc_unemplyed.csv&quot;, show_col_types = FALSE)</code></pre>
</div>
<div id="tidying-the-datasets" class="section level1">
<h1><strong>Tidying the Datasets</strong></h1>
<p>The tidying process was relatively uncomplicated. First, we had to condense the individually broken-up year columns into a singular one using pivoting functions. After this, string replacement was needed to format the year columns to not include extraneous information in the entries and to have them simply in the year digit format. From there, we re-coded column entries of numeric columns to be numeric rather than characters. We then removed redundant columns that did not contribute to the overall dataset. Lastly, we removed entries of the format “..” as this was how the dataset decided to encode missing values.</p>
<pre class="r"><code># GDP dataset tidying --&gt; Result: Tidy dataset w/o NA&#39;s -------------------------------
gne_clean_tidy &lt;- gne %&gt;%
   # remove the series code and series name column -&gt; redundant information
   select(-`Series Code`) %&gt;%
   select(-`Series Name`) %&gt;%
  
   # combine multiple year cols. into one
   # the range of years spans from 2001 to 2020
   pivot_longer(col = c(&quot;2001 [YR2001]&quot;:&quot;2020 [YR2020]&quot;), 
                names_to = &quot;year&quot;,
                values_to = &quot;gne&quot;) %&gt;% 
  
   # removes rows with a &quot;..&quot; entry on it = how NA&#39;s were coded in the sedate
   filter(!(gne == &quot;..&quot;)) %&gt;% 
    
   # format the year entries: ex: want 2000 not 2000 [YR2000]
   mutate(year = str_replace_all(year,&quot;.\\[.......&quot;, &quot;&quot;)) %&gt;% 
    
   # recode GNE and year entries as numeric 
   mutate(year = as.numeric(year), gne = as.numeric(gne)) %&gt;% 
    
   # recode col titles with confusing names to have clearer titles w/o spaces
   rename(country = `Country Name` , country_code = `Country Code`)

   
# Life Expectancy &amp; Nourishment dataset tidying --&gt; Result: Tide dataset done w/o NA&#39;s -
life_clean_tidy &lt;- life_expec_malnourish %&gt;%
  
   # remove series code due to containing redundant information
   select(-`Series Code`) %&gt;% 
  
   # recode series name to instead be type as in type of information
   rename(type = `Series Name`) %&gt;% 
  
   # do year tidying to make all year cols. info contained in one
   pivot_longer(col = c(&quot;2001 [YR2001]&quot;:&quot;2019 [YR2019]&quot;), # 
               names_to = &quot;year&quot;,
              values_to = &quot;stats&quot;) %&gt;%
  
   # removes rows with a &quot;..&quot; entry on it = how NAs were coded in the datset
   filter(!(stats == &#39;..&#39;)) %&gt;%
 
   # used str replacement properly format the year entries as 
   # we did in the gne dataset above
   mutate(year = str_replace_all(year,&quot;.\\[.......&quot;, &quot;&quot;)) %&gt;% 
    
   # recode to make year and stats entries all numeric 
   mutate(year= as.numeric(year), stats = as.numeric(stats)) %&gt;% 
  
   # recode col. titles to be more succinct and clear
   mutate(type = recode(type,&quot;Life expectancy at birth, total (years)&quot; =                            &quot;life_expectancy&quot;, 
            &quot;Prevalence of undernourishment (% of population)&quot; = &quot;malnourish_perc&quot;)) %&gt;%
  
   # make cols. filled with corresponding data for a 
   # country&#39;s life expectancy in years for a particular 
   # year and a country&#39;s % of the population that is 
   # malnourished for a particular year
   # The possible year range is from 2001 - 2019
   pivot_wider(names_from = type,
              values_from = stats) %&gt;%
  
   # rename country and country code cols. into a 
   # lowercase and w/o space format for ease of usage
   rename(country = `Country Name` , country_code = `Country Code`) 

  
# % Unemployed dataset tidying --&gt; Result: Tide dataset done w/o NA&#39;s ------------------
unemplyed_clean_tidy &lt;- perc_unemplyed %&gt;%
    
   # remove the series code and series name column 
   # due to containing redundant information
   select(-`Series Code`) %&gt;%
   select(-`Series Name`) %&gt;%
    
   # combine every individual year column into a singular one: 
   # the year range is 2001 - 2019
   pivot_longer(col = c(&quot;2001 [YR2001]&quot;:&quot;2019 [YR2019]&quot;),
               names_to = &quot;year&quot;,
              values_to = &quot;unemploy_rate&quot;) %&gt;%
    
   # removes rows with a &quot;..&quot; entry on it = how NAs were coded in the datset
   filter(!(unemploy_rate == &#39;..&#39;)) %&gt;%
    
   # used str replacement properly format the year entries as we 
   # did in the gdp dataset above
   mutate(year = str_replace_all(year,&quot;.\\[.......&quot;, &quot;&quot;)) %&gt;%
    
   # encode the entries in year and unemploy_rate to be numeric 
   mutate(year= as.numeric(year), unemploy_rate = as.numeric(unemploy_rate)) %&gt;%
  
    
   # rename country and country code cols. into a lowercase 
   # and w/o space format for ease of usage
   rename(country = `Country Name` , country_code = `Country Code`) 
  
   
#----- Joining -------------------------------------------------------------------------

   # first view what is missing between the datasets 
   missing &lt;- anti_join(gne_clean_tidy,unemplyed_clean_tidy, by = &quot;country&quot;)

   # stored the dataframe of missing information to a variable: 
   # this will be valuable for subsetting
   missing_countries &lt;- missing$country


   # remove the countries in the gne dataset that 
   # were not found in the missing_countrries dataframe
   gne_clean_tidy &lt;- gne_clean_tidy %&gt;%
   filter(!(country %in% missing_countries))


   # left join the gne dataset to the unemployment data set using three variables:
   # country, country code and year!
   final_dataset &lt;- left_join(gne_clean_tidy,unemplyed_clean_tidy, 
                              by = c(&quot;country&quot;,&quot;country_code&quot;  ,&quot;year&quot;))


   # left join the life expectancy + percent of the pop. malnourished dataset 
   # to the one we just created on line 142
   final_dataset &lt;- left_join(final_dataset,life_clean_tidy, by = c(&quot;country&quot;,
                                                                   &quot;country_code&quot;,
                                                                   &quot;year&quot;))

   # remove NAs that remained after completely joining all three datasets
   final_dataset &lt;- final_dataset %&gt;%
     drop_na()</code></pre>
</div>
<div id="exploratory-data-analysis" class="section level1">
<h1>Exploratory Data Analysis</h1>
<pre class="r"><code># Vis. 1--------------------------------------------------------------------------------
final_dataset %&gt;%
  # map unemployment rate to malnourishment percentage 
  ggplot(aes(unemploy_rate,malnourish_perc, color = ..x..)) +
  scale_x_log10() + # scale x-axis using log transform
  scale_y_log10() + # scale y-axis using log transform
  geom_point() +
  geom_smooth(colour = &quot;purple&quot;) + # color geom_smooth line
  # add labs 
  labs(title = &quot;Malnourishment Percentage vs. Unemployment Rate&quot;,
       subtitle = &quot; (% of the Population vs. % Total Workforce)&quot;,
       x = &quot;Log(Unemployment Rate (%) Total Working Population)&quot;,
       y = &quot; Log(Malnourishment Rate (% of Total Population))&quot;,
       color = &quot;Life Expectancy &amp;
Malnourishment Rate
  Log(Low - High)&quot;) +
  # add gradient color and stylings
    scale_color_gradient(low = &quot;white&quot;, high = &quot;orange&quot;) +
    theme_dark() +
    theme(plot.background=element_rect(fill=&quot;#ffffd8&quot;),
        legend.background = element_rect(colour=&quot;#ffb327&quot;,fill=&quot;white&quot;, 
                                         size=.5, linetype=&quot;solid&quot;),
        axis.text = element_text(colour = &quot;#b37400&quot;, face= &quot;bold&quot;),
        axis.title = element_text(colour = &quot;#b37400&quot;, face= &quot;bold&quot;),
        legend.text = element_text(colour = &quot;#b37400&quot;),
        legend.title = element_text(colour = &quot;#b37400&quot;, face = &quot;bold&quot;, size = 9),
        plot.title = element_text(colour = &quot;#b37400&quot;, face = &quot;bold&quot;),
        plot.subtitle = element_text(colour = &quot;#b37400&quot;))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre class="r"><code># Vis. 2-------------------------------------------------------------------------------
final_dataset %&gt;%
  # map GNE and life expectancy to one another 
  ggplot(aes(gne, life_expectancy, color = ..x..)) +
  geom_point( size = 2) +
  scale_x_log10() + # scale x-axis using log transform 
  geom_smooth(color = &quot;green&quot;) + #color geom_smooth line
  # add gradient color
  scale_color_gradient(low = &quot;light green&quot;, high = &quot;purple&quot;) +
  # add labs
   labs(title = &quot;Life Expectancy vs. Gross National Expenditure (GNE)&quot;,
       subtitle = &quot;(% of the Population vs. % of Total GDP)&quot;,
       x = &quot;Log(Life Expectancy (%) of Population)&quot;,
       y = &quot;Gross National Expenditure (% of Total GDP)&quot;,
       color = &quot;GNE&quot;) +
  # add color and stylings 
  theme_dark() +
  theme(plot.background=element_rect(fill=&quot;#f1edf2&quot;),
        legend.background = element_rect(colour=&quot;green&quot;,fill=&quot;white&quot;, 
                                         size=.5, linetype=&quot;solid&quot;),
        axis.text = element_text(colour = &quot;#507d2a&quot;, face = &quot;bold&quot;),
        axis.title = element_text(colour = &quot;#507d2a&quot;, face= &quot;bold&quot;),
        legend.text = element_text(colour = &quot;#507d2a&quot;),
        legend.title = element_text(colour = &quot;#507d2a&quot;, face = &quot;bold&quot;, size = 9),
        plot.title = element_text(colour = &quot;#507d2a&quot;, face = &quot;bold&quot;),
        plot.subtitle = element_text(colour = &quot;#507d2a&quot;))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-2.png" width="672" /></p>
<pre class="r"><code># Vis. 3-------------------------------------------------------------------------------
final_dataset %&gt;%
  filter(year == 2019) %&gt;%
  ggplot(aes(x = malnourish_perc, y = life_expectancy, color = unemploy_rate)) +
  geom_point(size = 5) +
  labs(title = &quot;Relationship between life expectancy, unemployment rate, 
  and malnourishment percentage in 2019&quot;, x = &#39;Malnourishment Percentage of Population&#39;, y = &quot;Life Expectancy in Years&quot;, color = &quot;Unemployment Rate by 
Percentage of Total Labor Force&quot;) +
  scale_x_continuous(breaks = seq(0,50,5)) +
  scale_y_continuous(breaks = seq(40,100,5))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-3.png" width="672" /></p>
<pre class="r"><code># Vis. 4-------------------------------------------------------------------------------
final_dataset %&gt;%
  group_by(year) %&gt;%
  summarize(avg_lifespan = mean(life_expectancy)) %&gt;%
  ggplot(aes(x = year, y = avg_lifespan)) +
  geom_point() +
  geom_smooth(method = &#39;lm&#39;) +
  labs(title = &#39;Average Life Expectancy per year&#39;, x = &#39;Year&#39;, y = &#39;Average Life Expectancy (Years)&#39;) + 
  scale_x_continuous(breaks = seq(2000,2020,2)) +
  scale_y_continuous(breaks = seq(68,74,1))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-4.png" width="672" /></p>
<pre class="r"><code># Vis. 5 -------------------------------------------------------------------------------
final_dataset %&gt;%
  group_by(year) %&gt;%
  summarize(gne = mean(gne)) %&gt;%
  ggplot(aes(x=year,y=gne)) +
  geom_line() +
  geom_smooth() +
  labs(title = &quot;Gross National Expenditure (GNE) vs. Year&quot;,
       x = &quot;Year&quot;, y = &quot;GNE (% of Total GDP)&quot;) +
  scale_x_continuous(breaks = seq(2000,2020,2)) + 
  scale_y_continuous(breaks = seq(68,74,1))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-5.png" width="672" /></p>
<pre class="r"><code># Vis. 6 -------------------------------------------------------------------------------
final_dataset %&gt;%
  ggplot(aes(x = life_expectancy, y = malnourish_perc, color = year)) +
  geom_point(stat = &quot;identity&quot;) +
  geom_smooth(color = &quot;blue&quot;) +
  labs(title = &quot;Life Expectancy vs. Malnourishment Percentage&quot;, 
       x = &quot;Life Expectancy&quot;, y = &quot;Malnourishment (%)&quot;) +
  scale_y_continuous(breaks = seq(0,70,10))</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-6.png" width="672" /></p>
<pre class="r"><code># Generating the correlation plot-------------------------------------------------------
numeric_only &lt;- final_dataset %&gt;%
  select_if(is.numeric)

cor(numeric_only, use = &quot;pairwise.complete.obs&quot;) %&gt;%
  # Save as a data frame
  as.data.frame %&gt;%
  # Convert row names to an explicit variable
  rownames_to_column %&gt;%
  # Pivot so that all correlations appear in the same column
  pivot_longer(-1, 
               names_to = &quot;other_var&quot;, 
               values_to = &quot;correlation&quot;) %&gt;%
  # Define ggplot (reorder values on y-axis)
  ggplot(aes(x = rowname, 
             y = ordered(other_var, levels = rev(sort(unique(other_var)))),
             fill = correlation)) +
  # Heat map with geom_tile
  geom_tile() +
  # Change the scale to make the middle appear neutral
  scale_fill_gradient2(low = &quot;yellow&quot;, mid = &quot;white&quot;, high = &quot;pink&quot;) +
  # Overlay values
  geom_text(aes(label = round(correlation,2)), color = &quot;black&quot;, size = 4) +
  # Angle the x-axis label to 45 degrees
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # Give title and labels
  labs(title = &quot;Correlation Matrix | Composite Tidy Dataset&quot;, 
       x = &quot;variable 1&quot;, y = &quot;variable 2&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-3-7.png" width="672" /></p>
<p>The most strongly correlated variables are malnourishment percentage and life expectancy, and this relationship is negative. GNE and unemployment rate share no correlation with the year variable. Life expectancy and GNE share a moderately correlated, negative relationship with one another and are reflected as such in the correlation plot. The visualization shows that the year and average life expectancy variables display a strong, positive linear relationship with one another despite the correlation matrix communicating that the correlation between these variables is minimal. The malnourishment percentage and unemployment rate did not share as significant a relationship as expected. In 2019, life expectancy, malnourishment, and unemployment percentage showed a moderately strong relationship that trends negatively. The relationship between life expectancy and malnourishment percentage was strong and linearly correlated. As life expectancy increased, the malnourishment percentage tended to decrease over time. There appeared to be no strong correlation between average GNE and year. However, there were notable fluctuations as time went on in the average GNE that resulted in it settling to a value lower than where it started.</p>
</div>
<div id="clustering" class="section level1">
<h1>Clustering</h1>
<pre class="r"><code># Making the binary variable
# Determined by taking the average life expectancy for the year 2019 in our dataset
avg_life &lt;- 71.04785

# Add binary variable classifying a country&#39;s life expectancy as
# Below or Above avg. based on the avg. life expectancy calculated from 
# entries corresponding to 2019
final_dataset &lt;- final_dataset %&gt;%
  mutate(above_avg_lifespan = ifelse(final_dataset$life_expectancy &gt; avg_life, 1, 0))

# Prepare data: Selecting numeric variables and scale them
final_scaled &lt;- final_dataset %&gt;%
  select_if(is.numeric) %&gt;%
  select(-above_avg_lifespan) %&gt;%
  scale

# Determine the optimal number of clusters 
cluster_viz &lt;- fviz_nbclust(final_scaled, pam, method = &quot;silhouette&quot;)
cluster_viz</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code># Apply the PAM clustering algorithm
pam_results &lt;- final_scaled %&gt;%
  pam(k = 2) 

# Save cluster assignment as a column in our dataset
final_pam &lt;- final_dataset %&gt;%
  mutate(cluster = as.factor(pam_results$clustering))

#Visualizing the clusters 
fviz_cluster(pam_results, data = final_dataset,
             palette = &quot;Paired&quot;, geom = &quot;point&quot;) +
  guides(shape = guide_legend(title = &quot;shape&quot;)) +
  ggtitle(label = &quot;Cluster Plot&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code># Observe the average silhouette width --&gt; 0.2710
pam_results$silinfo$avg.width</code></pre>
<pre><code>## [1] 0.2710735</code></pre>
<pre class="r"><code># Determine the medoids at the center of each cluster
pam_results$medoids</code></pre>
<pre><code>##            year        gne unemploy_rate life_expectancy malnourish_perc
## [1,]  0.1814206 -0.3044639    -0.1421260       0.4907740      -0.6943843
## [2,] -0.5505154  0.2575885    -0.4045916      -0.6368158       0.7628814</code></pre>
<p>The optimal number of clusters is two to maximize silhouette width. The average silhouette width is 0.2710, a weak structure that suggests that our clusters are not well separated and that observations belonging to one cluster are not that distant from the observations residing in the closest neighboring cluster. The medoid at the center of cluster 1 has the following values: year: 0.1814206, gne: -0.3044639, unemploy_rate: -0.1421260, life_expectancy: 0.4907740, and malnourish_perc: -0.6943843. The medoid at the center of cluster 2 has the following values: year: -0.5505154, gne: 0.2575885, unemploy_rate: -0.4045916, life_expectancy: -0.6368158, and malnourish_perc: 0.7628814.</p>
</div>
<div id="dimensionality-reduction-pca" class="section level1">
<h1>Dimensionality Reduction | PCA</h1>
<pre class="r"><code># Select the numeric columns in the dataset
final_reduced &lt;- final_dataset %&gt;%
  select_if(is.numeric)

# Perform PCA on all numeric variables in the dataset
pca &lt;- final_reduced %&gt;%
  select_if(is.numeric) %&gt;%
  scale %&gt;% 
  prcomp

# View PC&#39;s
pca</code></pre>
<pre><code>## Standard deviations (1, .., p=6):
## [1] 1.5950015 1.0619460 0.9971216 0.8760513 0.6378714 0.3995544
## 
## Rotation (n x k) = (6 x 6):
##                             PC1          PC2         PC3        PC4         PC5
## year               -0.158356233  0.006014414 -0.91614994  0.3614690  0.04921915
## gne                 0.244002820  0.556828937 -0.32505163 -0.7072773 -0.15567780
## unemploy_rate      -0.007503874  0.814461131  0.20846507  0.5067474  0.15171704
## life_expectancy    -0.580227020  0.009230498 -0.02465204 -0.2301573  0.13981907
## malnourish_perc     0.525734307 -0.120640609 -0.08374018 -0.0572400  0.80291501
## above_avg_lifespan -0.549790563  0.109174494  0.06271286 -0.2367641  0.53488499
##                            PC6
## year                0.04974019
## gne                 0.01639463
## unemploy_rate      -0.11544730
## life_expectancy    -0.76819395
## malnourish_perc    -0.23256813
## above_avg_lifespan  0.58285433</code></pre>
<pre class="r"><code># Create a scree plot to look at the percent variation explained by the PCs
fviz_eig(pca, addlabels = TRUE, 
         ylim = c(0, 50), barcolor = &quot;light blue&quot;, 
         barfill = &quot;pink&quot;) +
  ggtitle(label = &#39;Scree Plot&#39;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code># Observe the average silhouette width --&gt; 0.2710
pam_results$silinfo$avg.width</code></pre>
<pre><code>## [1] 0.2710735</code></pre>
<pre class="r"><code># Represent the clusters on PC1 and PC2
fviz_pca_ind(pca, label=&quot;none&quot;, habillage=final_dataset$above_avg_lifespan,
     addEllipses=TRUE, ellipse.level=0.95, palette = &quot;PuRd&quot;)</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<p>The first and second principal components explain 61.2 percent of the total variation in our data. Of the original variables in our dataset, the first principal component shows the strongest correlation to a country’s life expectancy and malnourishment percentage and a weak correlation to year, GNE, and unemployment rate. The entry corresponding to the malnourishment percentage is positive. In contrast, the value corresponding to life expectancy is negative, indicating that these variables are correlated but have opposite effects on one another. Scoring high on the first principal component indicates that a country’s life expectancy will be lower as its malnourishment rate increases and can be considered a measure of how long people’s lives in a country are as a function of how many people are malnourished. The second principal component strongly correlates with a country’s GNE and unemployment rate and is weakly correlated to year, life expectancy, and malnourishment percentage. These values are both positive, indicating that these metrics tend to change positively together; therefore, a country with a higher GNE also tends to have a higher percentage of unemployment. Cluster 1 had a negative PC1 value and a positive PC2 value indicating that countries in this cluster tended to have a higher life expectancy, lower malnourishment percentage, higher GNE, and a higher unemployment rate. Cluster 2 had a positive PC1 value and a positive PC2 value indicating that countries in this cluster tended to have higher lower life expectancies, higher malnourishment rates, higher GNE, and a higher unemployment rate.</p>
</div>
<div id="classification-and-cross-validation" class="section level1">
<h1>Classification and Cross Validation</h1>
<div id="logistic-regression-model" class="section level2">
<h2>Logistic Regression Model</h2>
<pre class="r"><code># Logistic Regression Model
fit_log &lt;- glm(above_avg_lifespan ~ unemploy_rate + malnourish_perc, 
               data = final_dataset, family = &quot;binomial&quot;)

# View model summary 
summary(fit_log)</code></pre>
<pre><code>## 
## Call:
## glm(formula = above_avg_lifespan ~ unemploy_rate + malnourish_perc, 
##     family = &quot;binomial&quot;, data = final_dataset)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0411  -0.5596   0.5247   0.6031   2.5738  
## 
## Coefficients:
##                  Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)      2.498975   0.115098  21.712   &lt;2e-16 ***
## unemploy_rate   -0.007706   0.008158  -0.945    0.345    
## malnourish_perc -0.218006   0.009048 -24.094   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3598.0  on 2691  degrees of freedom
## Residual deviance: 2396.3  on 2689  degrees of freedom
## AIC: 2402.3
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre class="r"><code># Calculate the predicted values using our log. reg. model 
final_pred &lt;- final_dataset %&gt;%
  mutate(prediction = predict(fit_log, type = &#39;response&#39;))

# Plotting the ROC Curve
ROC &lt;- ggplot(final_pred) +
  geom_roc(aes(d = above_avg_lifespan,
               m = prediction),
               n.cuts = 10)

# Visualizing ROC curve 
ROC</code></pre>
<p><img src="/project/project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code># Calculating AUC to assess our model accuracy --&gt; 0.8629
calc_auc(ROC)$AUC</code></pre>
<pre><code>## [1] 0.872006</code></pre>
</div>
<div id="k---fold-cross-validation" class="section level2">
<h2>K - Fold Cross Validation</h2>
<pre class="r"><code># Choose number of folds
k = 10 

final_reduced &lt;- final_dataset %&gt;%
  select_if(is.numeric) %&gt;%
  select(-life_expectancy)

# Randomly order rows in the dataset
data &lt;- final_reduced[sample(nrow(final_reduced)), ] 

# Create k folds from the dataset
folds &lt;- cut(seq(1:nrow(data)), breaks = k, labels = FALSE)

# Initialize a vector to keep track of the performance
perf_k &lt;- NULL

# Use a for loop to get diagnostics for each test set
for(i in 1:k){
  # Create train and test sets
  train &lt;- data[folds != i, ] # all observations except in fold i
  test &lt;- data[folds == i, ]  # observations in fold i
  
  # Train model on train set (all but fold i)
  final_log &lt;- glm(above_avg_lifespan ~ ., data = train, family = &quot;binomial&quot;)
  
  # Test model on test set (fold i)
  df &lt;- data.frame(
    predictions = predict(final_log, newdata = test, type = &quot;response&quot;),
    above_avg_lifespan = test$above_avg_lifespan)
  
  # Consider the ROC curve for the test dataset
  ROC &lt;- ggplot(df) + 
    geom_roc(aes(d = above_avg_lifespan, m = predictions))

  # Get diagnostics for fold i (AUC)
  perf_k[i] &lt;- calc_auc(ROC)$AUC
}

mean(perf_k) # --&gt; 0.8727</code></pre>
<pre><code>## [1] 0.8727329</code></pre>
<p>The average performance across 10 k folds was 0.8727, indicating that our model could predict whether a country’s life expectancy could be classified as above or below average when using all of the original variables, excluding the life expectancy and the categorical variables. This is comparable to the AUC value we received from the ROC curve generated from our linear model that predicts whether a country’s life expectancy is considered above average using only the malnourishment rate and unemployment percentage to predict it. Furthermore, there are no signs of overfitting, as k-fold cross-validation revealed that our model’s accuracy in predicting the unseen test data was slightly higher on average than the accuracy measured on the model trained on the full dataset. Interestingly, the model used for k-fold cross-validation included all of the original variables, excluding life expectancy, and obtained an accuracy that rivaled that of the logistic regression model that only used two variables to predict whether a country’s life expectancy was above average. This suggests that our dataset can obtain a high classification accuracy without an overcomplicated model.</p>
</div>
</div>
<div id="acknowledgements" class="section level1">
<h1>Acknowledgements:</h1>
<div id="team-contributions" class="section level2">
<h2>Team Contributions:</h2>
<ul>
<li><p>Jordan Toler: Full Effort</p></li>
<li><p>Tim Giang: Full Effort</p></li>
<li><p>Elizabeth Lam: Full Effort</p></li>
</ul>
</div>
<div id="citations" class="section level2">
<h2>Citations:</h2>
<p>Style: MLA9</p>
<blockquote>
<p>“Dictionary.net.” <em>Dictionary.net | Find Definitions and Meanings of Words</em>, <a href="https://www.dictionary.net/." class="uri">https://www.dictionary.net/.</a></p>
</blockquote>
<blockquote>
<p>Roser, Max, et al. “Life Expectancy.” <em>Our World in Data</em>, 23 May 2013, <a href="https://ourworldindata.org/life-expectancy." class="uri">https://ourworldindata.org/life-expectancy.</a></p>
</blockquote>
<blockquote>
<p>“World Development Indicators.” <em>DataBank</em>, 16 Sept. 2022, <a href="https://databank.worldbank.org/source/world-development-indicators." class="uri">https://databank.worldbank.org/source/world-development-indicators.</a></p>
</blockquote>
<p>&gt;&gt; The World Development Indicators database was used to manually create the customized datasets that made our project possible.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
